wireguard:
    wg0: ENC[AES256_GCM,data:R7636jhc2Umpu0OKX6qX9YhKhx5mpAsBMO8bUmFlWPss+UN8y71Qq8fJS988I6j+GaHU45+b33HFJWgY0lOMHuib1xXGWnnIB366pKbbDP+gxfMNZMVl98f3LdQR1Uwhbb/31vb3zwyM2QqeEWeCLvDZAoOGgkHGuAq5yV7KFkY/TDglVrUvKQEgxXP47SMPhppx+pgJYvq/o+YM+JwI8WyFBN1jgHU8KhG2wndhmk5wMUyWM9k6IOmnah16NHNLtaKIp8N2GeE/stPLNEJBgOtJxHsfkXQ5vtjsYpMNtuB3mhtjUpSpWBs7vpiJhWvRsDuHJPIzchA=,iv:k1Hx1XfrN4Mc/Tr60+2OvIGkiyYzIA4q/ONzINfmKjI=,tag:Qoq3l//C2n+l2FmMeaPLig==,type:str]
nix-serve:
    secretKeyFile: ENC[AES256_GCM,data:wM3aMXbZi+txJ8BotuiK4yQ8205pIGxvuDlo90vq3FhXJE0lspn0KF9T7rZV3Wx853aBBuGF2l7QbCdfoN2gg/JnY0i2QCNTblo4DpiTTX1tiOrnLsy/Zh9ufDPeVTNu7J4dNSJD,iv:9DFSaWKzQ5s+PHyBRY97GMzE35g8Xo4PEJdOV2Q7Jlg=,tag:r/Grvg4tPFlaVqvuWTelLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s3tnehfphy56y0wr4qgqevw6hjtynrvppd00fr2yn4wp2v5jp3ns78r9fj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQS93REQ4a2JJMzdqMmVW
            VElDc045enRicGpqUUM1R2JvcG5GQ0tic0JFCmJ3dzJTSE44MHY4cjc1NWJOVTE2
            eW1lMkFMN0NCQjl6YXlhdlM5dE5SM2sKLS0tIG1HbE9qL3N0OGxxSVc5WEFSRVh3
            Wk95a05wYWluejl5QTlhSGp6cWRVU1EKL4IoG/TywzXuRqgzkwIFb3NLwAaKcDvF
            LONoQl5KWLuQ4rxjARzzJ4tmFKA5lyXEmq6lkPWF3tewoICPFGkRWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-24T15:44:23Z"
    mac: ENC[AES256_GCM,data:xRki/6i/MKrsAQgRPm7klvxajUcVjPKpv1jnOY+Q7zpTGBKGSEtQ85Fc62ZrIIIWJgwbMkSkIYtoWwEyc8rRe6457m5z6lpUQYjw7u3UlF4I3M66PA24Y2pp8YChrLrjBPmHv60kiIMc1wLS6VGhX27ui7yqJxmwRezIqqWB2c8=,iv:SeNVYgfUJgYbOoCBLC/M9XVQmDwd0HQwfUPw6lOv+Gs=,tag:LNGmnrIOB2j4jd1TJW59Qg==,type:str]
    pgp:
        - created_at: "2024-02-24T12:26:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA9PPybZN0lBZAQv9E8kYK8gQntGlb3IATJTAgEU0rEKw5+VG+qPLC9yPqMn4
            f4ALgUx9PjRGmpYgpXsEobr6sMe/7NmnEpDxLqioS7aBFEdkPMhn2rxeiWFhnkAz
            kf8MDLCZzhZ3xo+nvgnGih8tHn0U6fU7KaKhR1xqbJG4XIIax11I4Rm6yQ+Y/ZwB
            J8ZkWAoemeBQzYaHsk5RnPMr2xAksQra5xjYp+QUftPKGpaU1ELkNGVuQqoPvQgx
            oQv1YFXmqxKhsWWSGzwIQm0RWPB0DzT8epj/F37a3P7pEoAwWQtGwvesITUo4E0t
            +O1AvdyaM7QryhZ1hO7ni0um5XgqAZA8S9AeViqCKhnD2YQbcGbXHIfDniUHwgFT
            n8WeoaspB4kHQ9lXg7SrpWGq+IDeUZsItpD0Fjl5txxwXIFZ7XbzSW68hspAanrD
            gHgUww8Av5hpuViTzO/QeuYlICvwSbYNbNc4jUaU/SFH1Ggb0ilDuP2+LehG7T18
            tkHKyPNfSiyAG3msFHHf0l4BI8K9ccYt5jN8J6P1NM9xuxHYjMd40jdf1CHqVX8b
            FMOrZ+yHAwBiCh3xfqt5tsyHg2ZNZIPzj3EGRoiIdiwoN5ODgxmwBdJGBiwpWQyO
            9ZcK4Dgew7lHLCH7ahsm
            =Ca57
            -----END PGP MESSAGE-----
          fp: 773DC99EDAF29D356155DC91269CF32D790D1789
    unencrypted_suffix: _unencrypted
    version: 3.8.1
