keys:
  - &juuso 8F84B8738E67A3453F05D29BC2DC6A67CB7F891F
  - &jesse 773DC99EDAF29D356155DC91269CF32D790D1789
  - &ponkila-ephemeral-beta age1rahna5rce9mj0js0p7dgt6wseqyzxjawva82tfdelzuvmngr5fdqa2geuy
creation_rules:
  - path_regex: nixosConfigurations/ponkila-ephemeral-beta/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
        - *juuso
        age:
        - *ponkila-ephemeral-beta
