netdata:
    health_alarm_notify.conf: ENC[AES256_GCM,data:c3PE3plR4BLr35gOj7HSdhQEyPioJZBDaA9DqGY7iZ96Flhr8M0q2U3gyydG8+HM6hn7ZK6U7Er9snf7ebT+j2/xs+hLC4PflwLZ7y21CwjrRioKAZTRsD9wes10Dpzw5/uX6k230AdN9YOXE20xfkaWv6WsDpqyTmRVFbgFrL9rXJWPixx2KqNxrsKKJHliBXENhNm5aiKQHzqE6hXGYnnXtmKPEk/Hf8T6Yhvw41NSycqj/IauZWALNOBDdINRdE7fgNVaeYOqNGuO74M+CRANiFID1qozqGfAqezSew==,iv:K1Suaw0/13CAHFEOZHUxN5pjxjeGP/Ne5HkoHkZS+qs=,tag:+mPGLUR/Wbad4u4U7fIFQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ruvl5ylz05flrh9x0ylxqcrmur2xdgv3k09km9fhd9pes75s3aqdzqmhv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cjNmNnVoN0ZncDZ2eEx4
            bkxqVVA5WWpraWdBZWRpY0k1c0liQTZpeGtZCncrLzVLdjdoS3hocFU0dDFTTWFy
            V1lKMWczbjlZNE1hRmVxMDRGaFhWRHcKLS0tIDIrTkt5Mm1XeEVlbzc4NlpDcWlm
            aE42Z1JycjlsK2t2UVN1TnlnZDNLeEkK+lzo6P1L5rT7GdXu3gWJ7VyZZNiTe/py
            8EIbxBvewlhUjzRBD0Yqwzjj8+dm4oojmD4molzbKTjlkpTItzC+Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-11T11:57:27Z"
    mac: ENC[AES256_GCM,data:nM9CNtCn+TYnnmIovXxHrxqcBLDcJN+ePTxxE+i8/V27Y1LBCC7aMctWTtoC/p4PlJYEr4Hwvuo/3nC66tQg7xSWp2xMfvtkblf3B5/CoJKozKh+9HmzFSKed5xzilvD+1A8sUWAd3p8SradIn5iXQIou4rXZdToVnCW+YQ2zwU=,iv:le9Ouw0kw3Pc9eFXBNDaWTHq6k0598WVtvudHN2s2ds=,tag:WxpLkImJ2s1HviAjQ/h7KQ==,type:str]
    pgp:
        - created_at: "2024-08-11T11:57:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hH4DfXeKk69lOL0SAgME3zlyWTSvnJZISMhEEfsaEJrZaarQx2UiaycOaEpgHh+R
            LaY9yPUZ1hZUY+bgCtX1mfWhTUIpUAewcI9NOcLrljDOtDTIxNAkdemrl3l/yqEI
            Gg7j/ghzbjpLnQBQJQc/0G8AcW5JiapMn61svByKJl3SXAHWepl7yTXHuq+Ww7aB
            NGUGdKitESL7UDhpqNT7RRpk52OHQ8hFAG5QI6OTiH9yw5F13N74HXUDG46zuPgP
            bCsaR1MLCf1/owOxAnPsQq/cePxftTeVuTuyPD+v
            =9xrP
            -----END PGP MESSAGE-----
          fp: 8F84B8738E67A3453F05D29BC2DC6A67CB7F891F
    unencrypted_suffix: _unencrypted
    version: 3.9.0
