cache-server:
    private-key: ENC[AES256_GCM,data:RW9y+Tf7u2zx0cNMgkIUAd3MEHXwrobG9/Svy2iTm/csh7M5m4VhFYFTq2DI6Gmb/H7efyjAC7piZr92yw0J0x9fFUR/3LUq6RzHz4ex9cd0LHj4E/cyJHi8OJ3y/KKJTDfwyZfNbefkpxw=,iv:B69HnspwuLHVIPjNLQD3QXCbfvD5VXhlWBAqJF89G5A=,tag:994OWqw39AHUEyuEqEY+ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age135sk8075lhw3u8qgncq7w9y9qjrjyvavvq8j7w8dewnew97xrsxs2cawxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MFVySWVUNlBYZkZ1d2ox
            SitOUHhjKzZWaFVFK0kvb1l3Qm5uOUNPckNZCmg0UzVBRmhCQ05RazEvZE40ZkZG
            aTF3TW1XVUdGdFpuT1JGcFFvSHhPMmsKLS0tIGRjSkcxL0NuRnFSNm9WY2ZpSWhQ
            cTU1TnhGdDVjeEkwWm56RzNLOUFtMEkKQo3wvYl1yYyiGAQc+Iefuz6CO7Vlg6rQ
            KQwAGnwVG/WHs91gCYp4rQftXNcCqBHGK4k1BvEWl4oGEQFXFaYqSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T22:56:29Z"
    mac: ENC[AES256_GCM,data:qDwMwhYjBwPg87AZDPlDXzY3RKy2/+rERLAesQXUXnfLoTMh+/6nCdzUVGXq/eQbSlggWVVaYNGpO40DIU6Kd9qYjoCfkd3fbhsd297OvgJc2smWgRTvO+1Sgg13xntmtKQpRs/Yysyxp2sE5hHwWChUYjji8dPKjylZh0IRkIs=,iv:L6vwH0CATJ/a6NsFs7li5bkFzwL224Pjp9s3auZp2TU=,tag:VtuZkjMVtTh9dqDSbFHIsQ==,type:str]
    pgp:
        - created_at: "2023-07-18T22:55:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA9PPybZN0lBZAQv8DSh9Y31V26Z5le8r5ZMKX5qJ965PZlku00DbM2xRdx0H
            2zn/cppl55BV9mljiRT4kC2dx8MvcJlCJQpfJ0NlqfHvhXVzmkyNAOy85OmmpyiT
            SS8jnAAg+/8IcSVvp9GdaPBRPvKGapubqGssZEfMqSMb9w39ksppDbxt6R+M2cpc
            nBMRhTnXinKj0QG4jeWBlyzNeh2l2ExgK5roBNZvbfY2UlnDihVvWj+qjG3AaNPN
            pAy3iD7hVTDl9y4qF2VdHiHvcUMEeit2GEIGITorTtB4Zk+7vCNUtKlTgJGXk/va
            1JeDPdfI7EUGmPgm/qmTP3oNKPunyG/jt3l6zPkO2WQpDsfrWE3nTu/01d8sFNkY
            zCgKAOU63a8Zu58TLrvlg0CJ9LdpNwNZC33y2RkPdC57lougkwq5yJaXx4b9BtA0
            jphYZ47JwHhLDoZ0I+y5xz0Ncxgs5ZwfuVEVMWmUODJ4YWvbEsCesgKcCrKrfAYX
            VoZV4/zV0Z+jkQG6DEe+0l4BMqT12CSjMa+vQQToB+H5XwxS10YPrLkdntcQMQcn
            fxGICUhV8PAFWtHac3Hds65xkmit1Vk/BSqbvOBtLfqVHA4tOMTkj0Pi3FYelQmy
            ZxrRcXCC7yQa7/qxJ6Ha
            =dVfr
            -----END PGP MESSAGE-----
          fp: 773DC99EDAF29D356155DC91269CF32D790D1789
    unencrypted_suffix: _unencrypted
    version: 3.7.3
