jwt.hex: ENC[AES256_GCM,data:etqfSD41Kw765jBgF6ydokIxYVy/B/Zg6ISUTZRmtUldRhHRCfa6sre2hhv8A0JIpeL6X6lTNmHTeuBQ34TPdw==,iv:6H2zrYniseChV5eCmAKh0eTWjhPYhoWpu57it7Zogxk=,tag:ct3sIqQm5W6CUySVXWTeTQ==,type:str]
wireguard:
    wg0: ENC[AES256_GCM,data:tumfSjp/Lf/lSUMFyyCeAfTHRjp+YWF+H862XCKg58cXFQxAcdIKPf7KaVuIfRLP2XfWomAvkCRQMBzIronGazEJP2ODJOOvNSVm/IKX67mP3UR67t+KEfgsCLOWX+dul4VFu3q/o8Ox2ApW8u1DYRVQaaumxR4WoWNx/SaVIqfW9D8haaW9k0m67MA7XO9PQojTMy1cBjhF0Awih5P6wMrAXArVwlAnGjDXwwlVvK3/NP9txhBtwFdmyimfCfsTjFdmm46MxYveSo8CP0eKmoOtrGmTOXOlwzNCvtH+mSv6f2PZAeSAu3ykTWsofzNwFRMfxFmQ54k=,iv:qfoczteRfxNAFwape0sT+qKjTww3VU99+JDz7wQBe8g=,tag:tDCueB/cdjt3CD5DamjRIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10256ff6jm2fqjekg4ta3y6ym6s63ppgxrnfrjlsnknd8jduksvasrgqnsy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYnhMeklDWE9XNTVHTFd5
            cUMvcWp3UFFCSnVrUDJIdDBVbHBFbytQampzCkRFTjFmNFJESnhDUWZTeU1Sa1d6
            Y1o1Q2hDQlFvamVNdm5WTDVRY2pEZmsKLS0tIFRDRkdkU1JBQzNVL1RucXpGMW85
            U1NqN2o3RzhOLzVTZGh3a0RnRlNYczgK7KWrCDrFmsewVglgDpO9IOfRxdGwFazW
            oXE/+x1UpLCVoVfGj7zvxRMUz69wJYt/AQnPA7c5M2jwb8nNUWqCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T17:47:10Z"
    mac: ENC[AES256_GCM,data:CPdODGUWEyhkw9dC/WrqJrY1eoJqf5LWMDbdwAULEX5dOA+C6u4TS8hY9tducceOP9ZFAOKYrTveR45qRjGz/OoOdWI2unMaT6+4COtEgi14Jw2X0bsQfaH8LeG9xQdyj9flDiyoOqJ4Lmd5HwByLnIWgtgAvTmzy3SbBaFwHxg=,iv:/Q5UzmeQwmz+svXbBUf+uZYtU5TdU2frjV0UejWg2iE=,tag:bV/pltvhn5qlvNib2dUmgQ==,type:str]
    pgp:
        - created_at: "2023-04-26T11:15:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hH4DfXeKk69lOL0SAgMEjGXeSa0XtQygLmHajQTy6bYd0yUeusDLb34rV5yq9WFa
            n6gU7I5vpJejG+F4PHrP1A5nsQtolAQcfNQhES5d7TDJSshDCoE/8JE9Xz0PviMh
            TTn3d9XS2GGNWLl9kPc6opIbvjoHs70mj52KPp91BxPSXgF2ulAh0kmj8VRGWvzw
            rl74bMBDQCpDAfGG0Izd1NiaI0Hn7FZDupA/Gn9BRBqYRBrX9NInQNVumP7G/I6Y
            Ic9F0xczNGEw1xSk/+eR+clVqHIfKncu1ItLoszqzlI=
            =89NM
            -----END PGP MESSAGE-----
          fp: 8F84B8738E67A3453F05D29BC2DC6A67CB7F891F
    unencrypted_suffix: _unencrypted
    version: 3.7.3
