netdata:
    health_alarm_notify.conf: ENC[AES256_GCM,data:BbDzQik/u01d+GokXeDU6YjJdU5YIHdT0hJ4EAUtetbJLOVy6/icBp78XByudY/UAFLSbnEiR6oSSDNlbDSOGd4ONF8cPyc6wlMQHJ1E7MY1uF+EF4o/1i9rCtJ/EMA7o6aQmapwELXycIG0hD/0emg7lPdFdV4n5I5AVS8rDH5tIwi9zjWYr64EsO1msAReOkvSDxnkqObelwNqo852Il7QWNnSlU5myQv9DhCQ4kT+fKkUrcMXIbjmPazCo2MirwQxSQ1mpqEVm6C8yMi48bHGl6qIO2qu0zrKhKN2LAvGU/Vngay/UHLy0Oc0ggCSANh6mS+J8Gx75pKNae+ve/z7Z5jQ7P2DMOwRk53sweIKnNllNVJXGD2/+gQ4S0ylF9TtGOLxzAj4KgGpi3SXww==,iv:nTOi9deiiFP7c9b15BQteoM0vlxFNmcfsDs0EaFZA2Q=,tag:WssWzHOQ1O1GWoRx1a6RyQ==,type:str]
wireguard:
    wg0: ENC[AES256_GCM,data:o7eiWZX7waVXYfTfs7uncPb7ZgkJETq/UvDrucpmsOr5bKKbk7sgfZeuqOsh4FWtxO67V/KZSjH79WrZVPOI6fonCuaPqDn84cxnyJQNmoZNZXvfGXOUi+V5PdHMDxkdSu1CM5jj9kFidHNvt3gkGA0Yt+S3L8CqFfwEiXc7p/Zl21jlVyLPTqDt/B8MOLKWFXNDwPc/ki94pj+5G19ZBrPclvxAkd1flz+e5BweBWcwNdYwvR4kpqjNve0IZ0jy2jKHj5WrtjYb+jecqysrg5E7tSgBg57yz7UhDf3CEMdWMzCifH2l7OKc/f/W08m0MkJS7ua3/Lhb,iv:ukXHOlVxVK/rE6lk1IF9p1CbG4gQOEUKn2RYHY6FJrI=,tag:/cbJNJYdJQVIiGM1582BkA==,type:str]
keep-network:
    operator-key: ENC[AES256_GCM,data:Wk1k39N11LlT7E7XC90raJIE6vEE1eTpCPxGxju9ulyMbzJBVrMC/dyoC+qj2RAYlLf8xg/HS8ugOj97lxsrQZ/BvW0GMbRpGJTXnjc4WQhhzjYRsfGZ/Ts6F4d6aOuAzBXfoTfCEvCMQp9mixmvBPrlXzbVCoZD8Z1lN/RHKK/69rpMh4BA7ZTJ5FmAdBcU7/gqTmX5Af+hHpnEEtgsvTsyiym5U+g0ynEvZOf4n7jKT+ducqyL0Q6H5kh3e4+tJx4PDl26VxTi8HlwDfFlpZ0ROGKaWsBXzVm0z9KYOiX83WKU0bHac2/py+LnEegaWZ/3ED3QC0DYyibsIVBBmigUqqiKQ7Mn2esjHtp6/Mdf1CD8r1mz2XpMCGLMyQGiyeFJtdQQZuAtyXi2e07PBJiWx+fFF4tQrsOnwHd+PL8PrSvxD0UX0sN9S/06C6NH+EALZgXioVbZKWitagUc3gK1vbZxTjLmVsgeBUcjE3BNFL7ssq5PwIUs+l458Udke5q03Gf/eRaEUp93VgpiMGmjEFaa94MmTwmBPl8+OGkpcoKsUQQ2+TNy+5NPZrgkKuAPfBFUfyVqf1PmSD1vCy8wFEkxkY67rCnvArBDtE5f6EsMHYdierTvmozNwIAubmxrjBakdZH7K8FF,iv:hOtw4FiaJuEflUQILmeTRMczP7mIbVD204LP4gcXbsk=,tag:OvqfBGL2cBMfHTLcRDnvOQ==,type:str]
    env: ENC[AES256_GCM,data:N78p88VfKSEcw7NOJ60vdZezW+C+z3Vf55BDyPQsn7iNWOyM2f94dA/e4FXnXHk=,iv:l20Mjp7zCQvXhpLysJ7albwSf3IXgA6aC2a/n2bs51I=,tag:/NwDjeuWcFL4bDBdmMYPlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12jm0kcs6vxffpr5k4gn899s05rhrvtw6fnm0m45ralck5sp8hyrs6qg0en
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cC90NEtmeWpoQ0RNTnRN
            WDFLY0NicGFiQks1VkZzVWdYNUM4b2FGaG40CkFLMHZ6Y3N3UVV0dkdqK0NLRkFx
            RzdEWmVnYUwvbjNTQjI2aHhVZFBSVmcKLS0tIGZMZEo1eE0zVmR5VjlsU3U0Zk03
            WFFjZkQwdUlObmpjWS91bk5SZTJvUGsK65/sq2eT3cKuFF74rt7g0OjaWicC1OD7
            r36QtI0PvURVpPb4GMqz+aAuDPj7BQNrd/AxLr3s/CcVZVADN7UE+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-20T22:08:42Z"
    mac: ENC[AES256_GCM,data:D7XkVCWB+N4Uc8GsiQZWHzvk1It1FXaHRkHn7TDqhQXBagJr1UDmoBxN2JpJ1DFo9gbnaq7qZpSsFZLCyzv4tmxYqBDTL2rnEBJDkAQSOKcCseSO+S4OVpm35dDJwsLtVUbIdNV0rM3kDFf566LAY1opw7+rE+L+9YXZ72Quito=,iv:NqeHKSmKLz+ETRD3B7+TYU3VWfUPI1LqbnVR+CGogIQ=,tag:uq2QQ69sKTSeL6wZGnsBLQ==,type:str]
    pgp:
        - created_at: "2024-02-18T22:22:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hH4DfXeKk69lOL0SAgMEljCwFvyU8kGYQus7wz6lT8dtqTGi/WsfIW53gvC/spR8
            OY9WP+QA0CUpGlWMPujNH9suhDURabZTy6m3FCjXMzCvO1aUuFC1gCZEVooNx0Kg
            j6bZbXGUa8Q+hb8PxwoDzYtKqziKdaAZ19BTPy086tzSXgHllNehCB4F8XeQpGg/
            mBFd3QEmTU2EU313N/P43cHco+Jzo2enaQ3MhDMovHCj+CJ5gUfwqOEtr7NAq6ls
            XJWXY0U6vbZ0j+1RFCu3lyWX0pOVXE/6i6aIYuXYMDY=
            =FY1D
            -----END PGP MESSAGE-----
          fp: 8F84B8738E67A3453F05D29BC2DC6A67CB7F891F
    unencrypted_suffix: _unencrypted
    version: 3.8.1
