wireguard:
    wg0: ENC[AES256_GCM,data:wqq0qcd+VdY7/SHk1jVQsja1akPnA272NDi9A9aqu450DSPySbi77f7hvllNVw==,iv:z3JJKOT43I8aH5zmfO3TUmKMgDbUL98JJi2LSHRoQNA=,tag:7Rywzpd7IiQ+8+ON5q7vYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12jm0kcs6vxffpr5k4gn899s05rhrvtw6fnm0m45ralck5sp8hyrs6qg0en
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cC90NEtmeWpoQ0RNTnRN
            WDFLY0NicGFiQks1VkZzVWdYNUM4b2FGaG40CkFLMHZ6Y3N3UVV0dkdqK0NLRkFx
            RzdEWmVnYUwvbjNTQjI2aHhVZFBSVmcKLS0tIGZMZEo1eE0zVmR5VjlsU3U0Zk03
            WFFjZkQwdUlObmpjWS91bk5SZTJvUGsK65/sq2eT3cKuFF74rt7g0OjaWicC1OD7
            r36QtI0PvURVpPb4GMqz+aAuDPj7BQNrd/AxLr3s/CcVZVADN7UE+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-18T22:22:50Z"
    mac: ENC[AES256_GCM,data:DmMdMc3YVLjiTIv2x20Zt7W5lhdLp3p79+Zm6rJ8rKOE3CEzkBMeXM9ogyi2STh+woFsLzxlzzL9aJld9XnzxknSDOqLQz5BVEpwGQ+V1/fGfNVZJ71VDBJbzLEHeZmmREpnqDi82ufIKDGcEmaLhBP4RSZr2GuSTb0iNv9ZxuY=,iv:Rs8LjRiYBpvdo7UtEmEokBqaZha8SvJ74OkcgKlR4y8=,tag:KCLDHbO/1trA8+ZvE5eBUg==,type:str]
    pgp:
        - created_at: "2024-02-18T22:22:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hH4DfXeKk69lOL0SAgMEljCwFvyU8kGYQus7wz6lT8dtqTGi/WsfIW53gvC/spR8
            OY9WP+QA0CUpGlWMPujNH9suhDURabZTy6m3FCjXMzCvO1aUuFC1gCZEVooNx0Kg
            j6bZbXGUa8Q+hb8PxwoDzYtKqziKdaAZ19BTPy086tzSXgHllNehCB4F8XeQpGg/
            mBFd3QEmTU2EU313N/P43cHco+Jzo2enaQ3MhDMovHCj+CJ5gUfwqOEtr7NAq6ls
            XJWXY0U6vbZ0j+1RFCu3lyWX0pOVXE/6i6aIYuXYMDY=
            =FY1D
            -----END PGP MESSAGE-----
          fp: 8F84B8738E67A3453F05D29BC2DC6A67CB7F891F
    unencrypted_suffix: _unencrypted
    version: 3.8.1
