wg-dinar: ENC[AES256_GCM,data:vibGdN0gbiR73vqM2KKVhfw4/wMQ5KFi9dj7HhsfQNMI6koG+P928ZEOiRbTp/ac+YxhjIUkqCGD+0ODTU+QLXkFmQpCgpKOCQVnNm9uEjdW3Qytb6LLNjxHv/1+oxSE7Wv2pRoRDJRuSy9uG8rydBFR4BBOiI0b+85f8Whiuvl73c3QHvCNpDgvwUg+D3C+r82dT/6CtOO1DRYe9uPAvO87QDa38bKyH73pVVEnhCMWumuFsQtHGekmavt0g8Y1ytlD7APLFPQ71LxJXXg2wVJiT1mHa9+c8g9RAQqChRW66IpIXpHJlAQdkQ9cP8HHVou91fZJovDDQA==,iv:eHhC2ZQJmy2M3R2+LUbExaczeUyqkyp6ErF1YV+TbTU=,tag:Q6iftv0xliyu5Fr6EpmC3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zayhap727avpeyc6w6n7k5aqfu7k7s7s9y0dr329xppanzsjrq0sca8p4e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOUFhUkRuNjdwajZkeXRN
            OFRhODY5L2VmZ3I2UXRYdzVTLzUyb2FEL3kwCkhJZzBlR2xLRzlEWG1FU0dlRlJQ
            bUw0UndXRHZVU3YwSXNxaG1Bd3NrMlEKLS0tIGdzZlpNcys0eWVJSU9pNDZHcitP
            ZHhxN3VsTGdRbDYwL0IyNUtWamRjc1EKZd5t8ADQyQP9xLD5KfjT8DLetHiNLw9E
            vP23wDAH+h7fPozpc46z9086d+YWnHzTPUprqNR39ioGK3XWDk341w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-28T10:07:18Z"
    mac: ENC[AES256_GCM,data:cy/u99+svvoPOJZJWe1qh0h1cJrWns40oC2GjIdMU1c8SDWd0/2arOtev5kiUloWUGVgmNOZc2Ocxw5/sFEvnCzm3SC04p7WPxMNj41vta9dm8UQAGntfHbibMXMG7n8TT2KEhXkMT0STzKUWweWq7LRphTsdpFFH/2w6JfAFco=,iv:mreSDyoGq3Iz56Nrf4f07fmjwZN+Npb0SS4rDgfXB4g=,tag:SgRw2kzNQ6yMFIP8WdQjWg==,type:str]
    pgp:
        - created_at: "2024-03-28T10:07:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA9PPybZN0lBZAQv7BLjPz+DjInxlh+KnW1f3C+RWL2SG4Q6VK0184HGESZsR
            SxqitSyur9KVgcQjCG2kbmD1CZmcAgnCUDuMsZHcASB9lTnmKUtPGOWKqDi0REgs
            mZB1gHY0dTlsoC459eszetiCDc5BsKquIrzBcoUEjltfZO64bTMON10Qcrq2O8dL
            b/lSVjggnobic4U1S+t5a8mOY8sNlmmSwIRBBPua5dc9lqHH045rBumac4snOn+K
            xB9oDNyPqGsP7UldttAdPWOz3wNa2IpJeRCPFXBvBv8GskJJcG1w27DrnzYOUeZt
            4CUaS+AQNc0ccU7OM1uKPbpk7+Ih4uDiTZ7NBYlK6ZCB1si/a3VcspDswFgB2lSC
            xXJdPAGzxoch82RWCXkXzhXxTyO6hrkq1ytBWyGgPiaLvaq9kSmmh1/OMzz84ZhO
            jyilBZnHFNk4mLSBHz9lNRtLYrawp+6ZYKr4kMtZAIdqU/H3J0HJKk5nMHap+iQ7
            dZuAynXQcDre0tJSK0P+0lwBtIs+L+EhGONo05pUZgGSITHjnG5y3Epo1GCWq+Wz
            1dV1klh5E8j0jhsxUHZLWVsBOmTWi6ll4Ow8V6ISNqDEDik9ig525YXEuq+Mew34
            i8iFKswrP2s0krDmDw==
            =JyBM
            -----END PGP MESSAGE-----
          fp: 773DC99EDAF29D356155DC91269CF32D790D1789
    unencrypted_suffix: _unencrypted
    version: 3.8.1
