jwt.hex: ENC[AES256_GCM,data:6biky4nAp+NW/LflaBZ+WeA4G4O8lnAMw+qbXVvXibbPfG2px9Dr1Rl9PKaSCSBHtN+xKY6LLIPkuGNsPmRwQg==,iv:uxgFKF+7CxoNdW50l3HIeUk+AcNKiomqmViatjbjcHw=,tag:pzVIT2f1n3kd7bRuaD1dSA==,type:str]
wireguard:
    wg0: ENC[AES256_GCM,data:hXybYrhnfDIT4txTSZBZZwtGr9siKyrk7E9lVCcjAvDqKHa5UY1AOBYV5BaQsb2jepIrsS7GsXdtF3O1mnPc+PR0LDSEivq01YURlm5Ypvz09KJD9ZMoAMMHk/hdnauG9WhcenfL2f3Kg4gIQR0bpMxiZN58QE8wXoyE5wxXwqHsf5U71z43nmlfho/v2Xxp6n7Nhgr3cCQyqGIqYs2GW5BNZW5JrPGominuJ6DkplwX8agxt8SAZpK+3tcc3xJdTC1811RUBnSN5JpRcl4pfoK/DNTaVH/xIcoWpb4L22hrLizulTBq36rq3Eds7ei2Ql7q8UA4lA4=,iv:8IcjAHieNOFnJeTTdo+62TioGUXpEfPm1qNINnhZ3UE=,tag:Hv8TSvyVlEk8Gey3DebMiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fuxy7v9jfgzz3p4f0k5gna8rhmgp792cmnyrzuum3zkssqn0rqmqq34p98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNnVHTVprczdnUEtpQi91
            SWdLZFR1a2JRUmxCK1FDdmZTR0t3KzVIcWxFClBEcVk2S2dNZVdDSnVJSjBzWkEv
            bDZ0VHpCbHNORkxRd0RJYkdMb2pSTUUKLS0tIHdNbzh1Q0JFaDJaZ1dxUmUyOHQw
            YmlmNWtkVE96eFdwRXVENUdYVUNUYlkK13RImrfhZzVv49QVajdQPA6TXNtkh5aE
            JZthPsUu91/PSzD121mIDxwe8W8L4xNsu/dk76PApw45reFregRCXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T21:35:02Z"
    mac: ENC[AES256_GCM,data:cooNrB1vwUR/nOG2xR/D1VtglHIhHbkI1mhyWg2aIEgxplb7tyyHYZ5nuoNJxCem0LuGnVaO2mohozqvk8+oxV13mXG2VCf3c7zjCIxixPjAOh5Ou5m+BhWar0Yj3TwGfk8VF7gfQr/XneDcPIzGBbiirYUg9TUIISoiZHomYc0=,iv:cTITG+DZdPIFeEt2CQ+/sQ6Le/MVTN8n7mQO0QctYX0=,tag:MifkvVfZYXNGr2K1xAne+w==,type:str]
    pgp:
        - created_at: "2023-05-10T21:34:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hH4DfXeKk69lOL0SAgME580/BWJbvm1hSlTzMqT41roOUsaWwqrPNY6G2Gik28UN
            XRRL63kMjbb/a39dxxM9k6m5Y1avzrSWfjKbG55peDD57oEU/B3m35mjSV72SREn
            +Uh/Vyji6aho8mmw517AqRDKiumtnRfojb2kuUM2mdHSXgEtm1AcJFnPUsBBIOXs
            9TO/wLTfsK1yZf/+uc49CXAeN7336oG4R+SZJJTBa0nQ6gj/ytTQ8r0Gd00NidBc
            dp6krqh5ZVGAZqNnnXpzWx6rUUoQg2evlIIFeu7hhlQ=
            =jt/1
            -----END PGP MESSAGE-----
          fp: 8F84B8738E67A3453F05D29BC2DC6A67CB7F891F
    unencrypted_suffix: _unencrypted
    version: 3.7.3
