wireguard:
    wg0: ENC[AES256_GCM,data:VpN61ac2jZLx80wDkscpLXI7pDePtgDtmAid21Q92HhvRUl4vRQWN62UDZJCrzTv9CobRr0B8hU34J26eF1E1WKHKwXOjAREqXEdam8tuUApS1Ko1tKeK82PsHBKvJ5bwYnzdDyMN3cKfl7FB0lQhlVHaUTmKKdYWsZDFtSTsrohJALDi+HFB2yaaMF90t/z4eAAfouhWtELNQaghQf90v7lFCIzc7JECA0u4ckvcKacdPx+G/GW1gHYozdvb5Ci4zllh0+9msVQshWqd2+q5eT046ie2ucfb3T3FrimVq6fcPkBZCg2ay8+wSnVZzUVnOMmZLGUp1zq,iv:BELpVb51mxooK/0+iIakv1Lzjde/fS3HhBk+W2MUTrw=,tag:vQJmWto6VUXnvqE5YWCv5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10256ff6jm2fqjekg4ta3y6ym6s63ppgxrnfrjlsnknd8jduksvasrgqnsy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYnhMeklDWE9XNTVHTFd5
            cUMvcWp3UFFCSnVrUDJIdDBVbHBFbytQampzCkRFTjFmNFJESnhDUWZTeU1Sa1d6
            Y1o1Q2hDQlFvamVNdm5WTDVRY2pEZmsKLS0tIFRDRkdkU1JBQzNVL1RucXpGMW85
            U1NqN2o3RzhOLzVTZGh3a0RnRlNYczgK7KWrCDrFmsewVglgDpO9IOfRxdGwFazW
            oXE/+x1UpLCVoVfGj7zvxRMUz69wJYt/AQnPA7c5M2jwb8nNUWqCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T11:16:02Z"
    mac: ENC[AES256_GCM,data:CzPz9EVbDzytJYpbT0SLuIr6bAgJmcMtDXVG7pcrTSKnCVjrkvTZX7hkVl9c/5cL5DmeE2PqOSZNxNh2fOlOT3AG/W6zMnusaAUNmdIbPVmvK80xMGy4nlU8rBN7DUDpfBfG29uqwWIthrIY3mcM0kgx4V8H5jcjBv42pZdz6UA=,iv:lFmKouhh/A7RocorTyTqXW+50P2oxdxHY/SRCCuYF+E=,tag:K48cHzC7nXN+bXMZ/GMb3g==,type:str]
    pgp:
        - created_at: "2023-04-26T11:15:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hH4DfXeKk69lOL0SAgMEjGXeSa0XtQygLmHajQTy6bYd0yUeusDLb34rV5yq9WFa
            n6gU7I5vpJejG+F4PHrP1A5nsQtolAQcfNQhES5d7TDJSshDCoE/8JE9Xz0PviMh
            TTn3d9XS2GGNWLl9kPc6opIbvjoHs70mj52KPp91BxPSXgF2ulAh0kmj8VRGWvzw
            rl74bMBDQCpDAfGG0Izd1NiaI0Hn7FZDupA/Gn9BRBqYRBrX9NInQNVumP7G/I6Y
            Ic9F0xczNGEw1xSk/+eR+clVqHIfKncu1ItLoszqzlI=
            =89NM
            -----END PGP MESSAGE-----
          fp: 8F84B8738E67A3453F05D29BC2DC6A67CB7F891F
    unencrypted_suffix: _unencrypted
    version: 3.7.3
