wireguard:
    wg0: ENC[AES256_GCM,data:i5MpjOkC8PfWBYny8wVY7O1oRKDSNlLPXdRJTQKg96EfD3pCJa2MM965hF48M8jhQQ4q+X/2IH6xic1FKCP1EQ335a4eytS1OR9jK3ZVK1FY11vahDb6FIsA+bgW5BqlXvF9xmtnvim82nVByY9jE03opNQ/Kdh4jEn3JI8rgXBIo61h+h2G7+QL7DnXnpe6lxeglo+uG6QFVJM6rJXEnTCJ2BWBjThXcZvpeCMmjeALtmZYgAcwQOrCDovwVAAWYtqa2AbOQyOMja4jywg1Onx7Lw941q5hHy45r3QBUYDJPR7t59s348GPk7uZQ5EAwbPmQS9zJkbk,iv:53VLvxtGi6NWpUvXuFlG5rgP/r+fKiywrA7RXLLgSLA=,tag:IpglhyRE6MFjeThjyQ+e9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rahna5rce9mj0js0p7dgt6wseqyzxjawva82tfdelzuvmngr5fdqa2geuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdTg0dTZ0N1o0clBsNjJq
            RU5FbXluY2hGa2JTalJiL2Iwdjd5QTRJK1FjCjJTbllUL3B4MXdkb2ZKQUQ3V3VN
            QUhhSDBicU4za2Jrb3JTQXhyaUNOakEKLS0tIEh2VXVsQUlFelVJZ1huYzlCcThq
            cmxrelpRYjY1WXhKT3ZnV2hMNjhNU0EKLq++MzFKHLRWSCLwfjhKvJJJVwZ539Kp
            3wl1vgDQ+n32ODbis+oUpewZIKNu6xoJfhb08QQA/GLFEIL5ySpDrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-11T13:30:47Z"
    mac: ENC[AES256_GCM,data:cOm64+J9C3HF8eGxNLKvrT954+yU2Pg/JBfCE5eNr/f2Irm31YLLSvFAQ7LyMakot9zBhuE1JIJo7E0eEhEpB9vSXsBuvfJKATltmkGMY0zRJSJqKl/hMRZ8zzXomS6yL5LjIPN8wdPEcNKqb8/xTyJ3sycFIUNGtRVkTKucRPc=,iv:AT+1G5bnJXiwb/ye4ad2zoUBSQjgV/rKujHnmZZVUu8=,tag:x0VzQnGtHV96rzcvRsGvvQ==,type:str]
    pgp:
        - created_at: "2023-04-10T13:28:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hH4DfXeKk69lOL0SAgMEo4MQ5fLa7/S0p7fLlU9H9KJK+nwKZ7u99xNI2mmfAUo7
            egpj3U4TRPPLSy5Y1ft3/N8IhZAqRVSCa5ourVItTDB0o5sSHbo1Jb6Otv8j2LCe
            zyazPpIfgGoTpZHxjkqe+M8J4XNom4fJ9CaO3qjEpiDSXAHKUgN3BErQ6OZrd5E+
            k5H2mDPRJNcA53Q7O5aiC/Vsj0xzqzdIt2AwI4vhRm88HHmSa4eqxga7XkNZJjXH
            e45xsN6G3ITjIDACI//rtgaV+oyC/9/k81clkiBU
            =4MpE
            -----END PGP MESSAGE-----
          fp: 8F84B8738E67A3453F05D29BC2DC6A67CB7F891F
    unencrypted_suffix: _unencrypted
    version: 3.7.3
