wireguard:
    wg0: ENC[AES256_GCM,data:m7IuBBWtGaIYMunKe3jEM9xB8tuNURXKW5HGSW1rnGum6GG9wrVZ9Kf8uTKIZii5AD+5PICXUeKMQKqd5cQ4TdhkFE4icWlmuaX0y4jeiKzS+cWUKBwsto2fGEW8/ykPVt24bDHAbSvQLwivr868tKOf921dlLiOiIg6+k3fZwgisRYYX9l+Y3foM8iAB2R/upjPSfUWs0sGcLymFM6hkxtMS/r0w2diRGgPgFSQwqSeGB6sq3SZLEG3JV0CREuVTWDpV6sBtdo8s5j77vz6/ioX7lIai2wAoZmGUJAONfinusYG1qAaSazhuz6LD4F3J0UdZQ1mWGs=,iv:0TYmiPYRVcqeinAouhpbpAaIezQzIf2QQw33Z3cqivg=,tag:78jorGSJj2349f/is9cRrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rahna5rce9mj0js0p7dgt6wseqyzxjawva82tfdelzuvmngr5fdqa2geuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdTg0dTZ0N1o0clBsNjJq
            RU5FbXluY2hGa2JTalJiL2Iwdjd5QTRJK1FjCjJTbllUL3B4MXdkb2ZKQUQ3V3VN
            QUhhSDBicU4za2Jrb3JTQXhyaUNOakEKLS0tIEh2VXVsQUlFelVJZ1huYzlCcThq
            cmxrelpRYjY1WXhKT3ZnV2hMNjhNU0EKLq++MzFKHLRWSCLwfjhKvJJJVwZ539Kp
            3wl1vgDQ+n32ODbis+oUpewZIKNu6xoJfhb08QQA/GLFEIL5ySpDrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-25T18:48:35Z"
    mac: ENC[AES256_GCM,data:0wfncd9HxjyhfH5r8KkPabcXw8vPvrj7hmaqlIF9gvf/e5R3wH8/EiP8xXN2uRU2VdZ/Xz3mriQWJnNasXoZHTkgu6LAVeFqEhov6ars/jT3lp32QBMKGSCQ3n4Od7jy+4+NW9ovsElcNvXjWz9VCfPrZleieeWR6zlZVERy7qA=,iv:KSfhcPxM0YRLnKTLFjok3Psoe/+cgjlT55Y7kvk8u9c=,tag:b0tRMZGvDHuRMbiqu+RNyA==,type:str]
    pgp:
        - created_at: "2023-04-10T13:28:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hH4DfXeKk69lOL0SAgMEo4MQ5fLa7/S0p7fLlU9H9KJK+nwKZ7u99xNI2mmfAUo7
            egpj3U4TRPPLSy5Y1ft3/N8IhZAqRVSCa5ourVItTDB0o5sSHbo1Jb6Otv8j2LCe
            zyazPpIfgGoTpZHxjkqe+M8J4XNom4fJ9CaO3qjEpiDSXAHKUgN3BErQ6OZrd5E+
            k5H2mDPRJNcA53Q7O5aiC/Vsj0xzqzdIt2AwI4vhRm88HHmSa4eqxga7XkNZJjXH
            e45xsN6G3ITjIDACI//rtgaV+oyC/9/k81clkiBU
            =4MpE
            -----END PGP MESSAGE-----
          fp: 8F84B8738E67A3453F05D29BC2DC6A67CB7F891F
    unencrypted_suffix: _unencrypted
    version: 3.7.3
